apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # דואג שתמיד יהיו פודים למעלה בזמן עדכון (Zero downtime)
      maxSurge: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-container
        # ה-Jenkins יעלה לפה את התמונה ואנחנו נמשוך אותה
        image: localhost:5000/nestjs-app:latest 
        imagePullPolicy: Always
        env:
        - name: SECRET_KEY
          value: "my-super-secret-jwt-key"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        # בדיקה שהפוד מוכן לקבל טראפיק
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        # בדיקה שהפוד חי ולא נתקע
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10